version: '3.8'

services:
  # PostgreSQL Database
  postgres-db:
    image: postgres:15
    container_name: movie-db
    environment:
      POSTGRES_USER: movieuser       # Must match application.properties
      POSTGRES_PASSWORD: moviepass   # Must match application.properties
      POSTGRES_DB: moviedb         # Must match application.properties
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movieuser -d moviedb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis-cache:
    image: redis:7-alpine
    container_name: movie-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: # This named volume persists database data across container restarts

